Repository tanliyon/gym-xiangqi, pull requests merged in 2021-04, with the labels that each got.

#47 Publish to pypi
  .gitignore
  MANIFEST.in
  README.md
  gym_xiangqi/agents/__init__.py
  gym_xiangqi/agents/random_agent.py
  gym_xiangqi/agents/random_agent_test.py
  gym_xiangqi/examples/__init__.py
  gym_xiangqi/examples/agent_v_agent_demo.py
  publish_package.py
  setup.cfg
  test/agent_env_test.py
  test/latency_test.py
Labels: enhancement, merge-me

#49 Add "user vs. agent" game mode
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/examples/game_mode.py
  gym_xiangqi/piece.py
  gym_xiangqi/test/piece_test.py
  gym_xiangqi/xiangqi_game.py
Labels: bug fix, enhancement, merge-me

#51 Refactor and tidy up xiangqi_env.py
  .github/workflows/main.yml
  gym_xiangqi/agents/random_agent.py
  gym_xiangqi/agents/random_agent_test.py
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/examples/game_mode.py
  gym_xiangqi/piece.py
  gym_xiangqi/test/piece_test.py
  gym_xiangqi/test/xiangqi_env_test.py
  gym_xiangqi/utils.py
  gym_xiangqi/xiangqi_game.py
  test/latency_test.py
Labels: enhancement, merge-me

#50 Enhance PyPI build and deploy workflow
  .github/workflows/deployment.yml
  .github/workflows/main.yml
  gym_xiangqi/board.py
  gym_xiangqi/constants.py
  gym_xiangqi/piece.py
  gym_xiangqi/sound.py
  publish_package.py
Labels: enhancement, merge-me

#54 Add game state hash check
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/examples/game_mode.py
  gym_xiangqi/test/xiangqi_env_test.py
Labels: enhancement, merge-me

#56 Add documentation using Sphinx
  docs/Makefile
  docs/api.rst
  docs/conf.py
  docs/examples.rst
  docs/gui.rst
  docs/images/gui.png
  docs/index.rst
  docs/installation.rst
  docs/make.bat
  gym_xiangqi/envs/xiangqi_env.py
  requirements-docs.txt
Labels: enhancement

#57 Modify build config to create v0.3.0
  .github/workflows/publishing.yml
  setup.cfg
Labels: enhancement, merge-me

#58 Fix trigger condition of publish workflow
  .github/workflows/publishing.yml
Labels: bug fix, merge-me

#60 Fix check fails
  .github/workflows/publishing.yml
Labels: bug fix

#59 Update repository documentation
  CONTRIBUTING.md
  README.md
  requirements.txt
Labels: documentation, enhancement, merge-me

#61 Create dependabot configuration
  .github/dependabot.yml
Labels: enhancement

#65 Update LICENSE to GNU LGPL v3.0
  LICENSE
Labels: documentation, merge-me

#67 Prepare for 1.0.0 release candidate publishing 0
  README.md
  pyproject.toml
  setup.cfg
  setup.py
  test/piece_test.py
  test/utils_test.py
  test/xiangqi_env_test.py
Labels: enhancement

#68 Fix license info in setup.cfg
  setup.cfg
Labels: bug fix, documentation

#69 Fix unrecognized license info
  setup.cfg
Labels: bug fix, documentation

#70 Change publishing workflow verification step
  .github/workflows/publishing.yml
Labels: bug fix, merge-me

#75 Fix half-working environment's reset method
  gym_xiangqi/envs/xiangqi_env.py
  test/xiangqi_env_test.py
Labels: bug fix

#72 Remove Jiang points
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  test/xiangqi_env_test.py
Labels: bug fix, merge-me

#73 Add a test for env step_user method
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/xiangqi_game.py
  test/xiangqi_env_test.py
Labels: bug fix, enhancement, merge-me

#74 Update Python dependencies in requirements.txt and build system
  requirements.txt
  setup.py
Labels: bug fix, documentation, enhancement, merge-me

#77 Bump soldiers' points after river
  gym_xiangqi/envs/xiangqi_env.py
  test/xiangqi_env_test.py
Labels: bug fix, enhancement

#78 Add player-v-agent entry point
  setup.cfg
Labels: enhancement, merge-me
