Repository tanliyon/gym-xiangqi, pull requests merged in 2021-02, with the labels that each got.

#4 Create build system and add LICENSE
  LICENSE
  pyproject.toml
  setup.cfg
  setup.py
Labels: documentation, enhancement

#6 Add dependency list to setup.cfg
  setup.cfg
Labels: bug

#10 Add Python Lint to Github Action
  .github/workflows/lint.yml
  examples/demo.py
  gym_xiangqi/__init__.py
  gym_xiangqi/envs/__init__.py
  gym_xiangqi/envs/xiangqi_env.py
Labels: enhancement, merge-me

#8 Create Random Agent
  .github/workflows/main.yml
  .gitignore
  README.md
  agents/random_agent.py
  agents/random_agent_test.py
  gym_xiangqi/envs/xiangqi_env.py
  requirements.txt
Labels: enhancement, merge-me

#7 Setup initial skeleton files for Xiangqi game implementation
  gym_xiangqi/pieces.py
  gym_xiangqi/xiangqi_game.py
Labels: enhancement, merge-me

#11 Add Python code coverage
  .github/workflows/main.yml
  .gitignore
  requirements.txt
Labels: enhancement, merge-me

#12 Add Radon Analysis to CI
  .github/workflows/radon.yml
  requirements.txt
  setup.cfg
Labels: enhancement, merge-me

#13 Update Readme
  README.md
  resources/xiangqi_board.png
Labels: documentation, merge-me
