Repository tanliyon/gym-xiangqi, pull requests merged in 2021-03, with the labels that each got.

#14 Add environment observation and action space
  .github/workflows/main.yml
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/piece.py
  gym_xiangqi/pieces.py
  gym_xiangqi/test/piece_test.py
  gym_xiangqi/test/utils_test.py
  gym_xiangqi/test/xiangqi_env_test.py
  gym_xiangqi/utils.py
  gym_xiangqi/xiangqi_game.py
Labels: enhancement, merge-me

#16 Delete redundant unit tests
  .github/workflows/main.yml
Labels: merge-me

#17 Add unit test for general and advisor
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/test/piece_test.py
Labels: enhancement, merge-me

#18 Add unit tests for elephant and horse
  gym_xiangqi/constants.py
  gym_xiangqi/test/piece_test.py
Labels: enhancement, merge-me

#20 Add unit tests for soldier, cannon and chariot.
  gym_xiangqi/test/piece_test.py
Labels: enhancement, merge-me

#21 Add latency report
  .github/workflows/main.yml
  test/latency_test.py
Labels: enhancement, merge-me

#19 Implement step() method
  agents/random_agent.py
  agents/random_agent_test.py
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/piece.py
  gym_xiangqi/test/xiangqi_env_test.py
  gym_xiangqi/utils.py
  test/latency_test.py
Labels: enhancement, merge-me

#30 Add changes to dkim/pygame_update branch
  .github/workflows/main.yml
  gym_xiangqi/board.py
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/piece.py
  gym_xiangqi/xiangqi_game.py
Labels: enhancement, merge-me

#29 Dkim/pygame update
  .github/workflows/main.yml
  gym_xiangqi/board.py
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/images/black_pieces/.DS_Store
  gym_xiangqi/images/black_pieces/ADV.png
  gym_xiangqi/images/black_pieces/ADV_S.png
  gym_xiangqi/images/black_pieces/CAN.png
  gym_xiangqi/images/black_pieces/CAN_S.png
  gym_xiangqi/images/black_pieces/CHR.png
  gym_xiangqi/images/black_pieces/CHR_S.png
  gym_xiangqi/images/black_pieces/ELE.png
  gym_xiangqi/images/black_pieces/ELE_S.png
  gym_xiangqi/images/black_pieces/GEN.png
  gym_xiangqi/images/black_pieces/GEN_D.png
  gym_xiangqi/images/black_pieces/GEN_S.png
  gym_xiangqi/images/black_pieces/HRS.png
  gym_xiangqi/images/black_pieces/HRS_S.png
  gym_xiangqi/images/black_pieces/SOL.png
  gym_xiangqi/images/black_pieces/SOL_S.png
  gym_xiangqi/images/board/.DS_Store
  gym_xiangqi/images/board/BOARD.png
  gym_xiangqi/images/red_pieces/.DS_Store
  gym_xiangqi/images/red_pieces/ADV.png
  gym_xiangqi/images/red_pieces/ADV_S.png
  gym_xiangqi/images/red_pieces/CAN.png
  gym_xiangqi/images/red_pieces/CAN_S.png
  gym_xiangqi/images/red_pieces/CHR.png
  gym_xiangqi/images/red_pieces/CHR_S.png
  gym_xiangqi/images/red_pieces/ELE.png
  gym_xiangqi/images/red_pieces/ELE_S.png
  gym_xiangqi/images/red_pieces/GEN.png
  gym_xiangqi/images/red_pieces/GEN_D.png
  gym_xiangqi/images/red_pieces/GEN_S.png
  gym_xiangqi/images/red_pieces/HRS.png
  gym_xiangqi/images/red_pieces/HRS_S.png
  gym_xiangqi/images/red_pieces/SOL.png
  gym_xiangqi/images/red_pieces/SOL_S.png
  gym_xiangqi/piece.py
  gym_xiangqi/test/xiangqi_env_test.py
  gym_xiangqi/xiangqi_game.py
Labels: enhancement, merge-me

#31 Add RandomAgent vs RandomAgent demo
  .github/workflows/main.yml
  agents/random_agent.py
  agents/random_agent_test.py
  examples/agent_v_agent_demo.py
  examples/demo.py
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
Labels: enhancement, merge-me

#32 Implement environment reset method
  gym_xiangqi/envs/xiangqi_env.py
Labels: enhancement, merge-me

#35 Implement environment close and seed methods
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/test/xiangqi_env_test.py
Labels: enhancement, merge-me

#34 Add agent-env integration test
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/test/xiangqi_env_test.py
  test/agent_env_test.py
Labels: enhancement, merge-me

#36 Dkim/black images
  gym_xiangqi/images/black_pieces/.DS_Store
  gym_xiangqi/images/black_pieces/ADV.png
  gym_xiangqi/images/black_pieces/ADV_S.png
  gym_xiangqi/images/black_pieces/CAN.png
  gym_xiangqi/images/black_pieces/CAN_S.png
  gym_xiangqi/images/black_pieces/CHR.png
  gym_xiangqi/images/black_pieces/CHR_S.png
  gym_xiangqi/images/black_pieces/ELE.png
  gym_xiangqi/images/black_pieces/ELE_S.png
  gym_xiangqi/images/black_pieces/GEN.png
  gym_xiangqi/images/black_pieces/GEN_D.png
  gym_xiangqi/images/black_pieces/GEN_S.png
  gym_xiangqi/images/black_pieces/HRS.png
  gym_xiangqi/images/black_pieces/HRS_S.png
  gym_xiangqi/images/black_pieces/SOL.png
  gym_xiangqi/images/black_pieces/SOL_S.png
  gym_xiangqi/images/board/.DS_Store
  gym_xiangqi/images/red_pieces/.DS_Store
Labels: enhancement

#37 Add more Xiangqi rules to env
  gym_xiangqi/constants.py
  gym_xiangqi/envs/xiangqi_env.py
  gym_xiangqi/test/xiangqi_env_test.py
Labels: enhancement, merge-me, question

#42 Refactor and clean code from PR #39
  gym_xiangqi/constants.py
  gym_xiangqi/images/black_pieces/ADV.png
  gym_xiangqi/images/black_pieces/ADV_S.png
  gym_xiangqi/images/black_pieces/CAN.png
  gym_xiangqi/images/black_pieces/CAN_S.png
  gym_xiangqi/images/black_pieces/CHR.png
  gym_xiangqi/images/black_pieces/CHR_S.png
  gym_xiangqi/images/black_pieces/ELE.png
  gym_xiangqi/images/black_pieces/ELE_S.png
  gym_xiangqi/images/black_pieces/GEN.png
  gym_xiangqi/images/black_pieces/GEN_D.png
  gym_xiangqi/images/black_pieces/GEN_S.png
  gym_xiangqi/images/black_pieces/HRS.png
  gym_xiangqi/images/black_pieces/HRS_S.png
  gym_xiangqi/images/black_pieces/SOL.png
  gym_xiangqi/images/black_pieces/SOL_S.png
  gym_xiangqi/images/board/BOARD.png
  gym_xiangqi/images/red_pieces/ADV.png
  gym_xiangqi/images/red_pieces/ADV_S.png
  gym_xiangqi/images/red_pieces/CAN.png
  gym_xiangqi/images/red_pieces/CAN_S.png
  gym_xiangqi/images/red_pieces/CHR.png
  gym_xiangqi/images/red_pieces/CHR_S.png
  gym_xiangqi/images/red_pieces/ELE.png
  gym_xiangqi/images/red_pieces/ELE_S.png
  gym_xiangqi/images/red_pieces/GEN.png
  gym_xiangqi/images/red_pieces/GEN_D.png
  gym_xiangqi/images/red_pieces/GEN_S.png
  gym_xiangqi/images/red_pieces/HRS.png
  gym_xiangqi/images/red_pieces/HRS_S.png
  gym_xiangqi/images/red_pieces/SOL.png
  gym_xiangqi/images/red_pieces/SOL_S.png
  gym_xiangqi/piece.py
  gym_xiangqi/xiangqi_game.py
Labels: merge-me
